### PR TITLE
[tools] fix build on opensuse 15.3

### PR DESCRIPTION
**Pull request by fabbione**
tickle_tcp.c: In function ‘send_tickle_ack’:
tickle_tcp.c:60:26: error: ‘phdr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   sum += (uint32_t)ntohs(*data);
                          ^
tickle_tcp.c:60:26: error: ‘*((void *)&phdr+2)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
tickle_tcp.c:60:26: error: ‘*((void *)&phdr+4)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
tickle_tcp.c:60:26: error: ‘*((void *)&phdr+6)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors
gmake[3]: *** [Makefile:697: tickle_tcp.o] Error 1

Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

### CODE REVIEW

File: tools/tickle_tcp.c [hunk 1]
```diff
@@ -53,9 +52,12 @@ int send_tickle_ack(const sock_addr *dst,
 		    uint32_t seq, uint32_t ack, int rst);
 static void usage(void);
 
-uint32_t uint16_checksum(uint16_t *data, size_t n)
+static uint32_t uint16_checksum(uint16_t *data, size_t n)
 {
 	uint32_t sum=0;
+	if (!*data) {
+		return -1;
```
Comment (oalbrigt) [inline tools/tickle_tcp.c:59]: You should catch this where the function is called.

**Review by oalbrigt — APPROVED** [review]

**Comment by oalbrigt** [comment]
Thanks.
